create table audits
(autid_id number generated by default as identity primary key,
                    table_name varchar2(255),
                    transaction_name varchar2(10),
                    by_user varchar2(30),
                    transaction_date date
);